apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: irzrh553f-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: irzrh553f-go 
  name: irzrh553f-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: irzrh553f-go 
